version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/.github/workflows'
    schedule:
      interval: daily
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
